FROM node:16

RUN mkdir -p /usr/src/app/upload
RUN mkdir -p /usr/src/app/upload/pdf
RUN mkdir -p /usr/src/app/upload/img
RUN mkdir -p /usr/src/app/upload/video

# Create app directory
WORKDIR /usr/src/app
